name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-interaction --no-ansi

      - name: Lint with flake8 and isort
        run: |
          poetry run isort --check-only .
          poetry run flake8 .

      - name: Run tests
        run: |
          poetry run pytest --maxfail=1 --disable-warnings -q
